# Generated by Django 4.2.7 on 2025-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itr',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='itr',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='itr',
            name='business_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itr',
            name='deduction_80c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itr',
            name='deduction_80d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itr',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itr',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itr',
            name='other_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itr',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itr',
            name='salary_income',
            field=models.FloatField(default=0),
        ),
    ]
