# Generated by Django 4.2.7 on 2025-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0002_remove_itr_updated_at_itr_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itr',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='itr_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='itr',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='itr_documents/bank/'),
        ),
        migrations.AddField(
            model_name='itr',
            name='form_16',
            field=models.FileField(blank=True, null=True, upload_to='itr_documents/form16/'),
        ),
        migrations.AddField(
            model_name='itr',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='itr_documents/pan/'),
        ),
    ]
