# Generated by Django 4.2.7 on 2025-12-31 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itr', '0003_itr_aadhaar_card_itr_bank_statement_itr_form_16_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itr',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='itr',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='itr',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='itr',
            name='pan',
        ),
        migrations.AlterField(
            model_name='itr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
