# Generated by Django 4.2.7 on 2026-01-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0004_remove_itr_aadhaar_remove_itr_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itr',
            name='gross_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itr',
            name='tax_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itr',
            name='taxble_icome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itr',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
