# Generated by Django 4.2.7 on 2026-01-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0005_itr_gross_income_itr_tax_payable_itr_taxble_icome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itr',
            old_name='taxble_icome',
            new_name='taxable_income',
        ),
        migrations.RenameField(
            model_name='itr',
            old_name='total_deductions',
            new_name='total_deduction',
        ),
    ]
